//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.28 at 07:14:46 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:iso:std:iso:20022:tech:xsd:pain.008.002.02", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.jost_net.OBanToo.SEPA.Nachricht.pain_008_002_02;
